[supervisord]
logfile = logs/supervisord.log  ; 로그파일 설정 (배포 시 절대 경로로 변경 필요)
pidfile = /tmp/supervisord.pid

[inet_http_server]
port=*:9001

[supervisorctl]
serverurl=http://localhost:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program: worker]
command=venv/bin/python3 src/main.py  ; 배포 시 절대 경로로 변경 필요
process_name=%(program_name)s ; 프로세스의 이름 지정
numprocs=1                    ; 프로세스 시작 개수
directory=%(here)s 	      ;프로세스 실행 전에 작업 디렉토리로 이동하는 경로 지정 (supervisord.conf 파일 위치 기준)
autostart=true                ; Suervisord가 시작될 때 프로그램을 자동으로 시작하도록 설정
autorestart=true              ; 프로그램이 예기치 않게 종료되면 자동으로 재시작하도록 설정
startsecs=10                  ; 프로세스 실행 후 최소 정상 작동 시간(초) 설정
startretries=3                ; 프로세스의 시도 횟수 설정
exitcodes=0,2                 ; 프로세스 종료 코드 중에서 예상되는종료 코드를 지정. (0: 정상종료, 2: 예상되는 종료 코드)
stopsignal=QUIT               ; 프로세스 종료할 때 사용할 시그널 설정
stopwaitsecs=10               ; 프로세스 stop 할 때 기다리는 최대 시간(초) 설